### ISSUE TITLE
Masterlist Search Utility Enhancments

### ISSUE THREAD

**Issue by kymckay** [loot/loot#102]
Here's an example output from the search utility (oblivion list):

```
  - name: "RealitySpectre'sBetterPotions.esp"
    tag:
      - Graphics
    dirty:
      - crc: 3902031737
        util: {}
```

I was wondering if it is possible to show references as the actual reference text (in this case `*dirtyUtil`)?
Also if plugin names could be displayed as they are in the list (double apostrophe + single quotes containing the string)?

Obviously these aren't pressing issues, but it's just handy to see the raw data. Also means it can be copy pasted exactly as it appears in the list for various uses.
