### ISSUE TITLE
Unable to Assign Groups to default group ESM

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1084]
![test](https://user-images.githubusercontent.com/1944639/52316189-31ec5480-29b2-11e9-9502-912dbf5bb6ed.gif)

Build used:
https://bintray.com/loot/snapshots/download_file?file_path=loot_0.14.2-15-g4682a2a_cpp-refactor.7z

**Comment by Ortham** [comment]
I can't replicate this... Does it happen for you with any other plugins?

**Comment by CptMcSplody** [comment]
[Alpine Forest of Whiterun Valley.esp](https://www.nexusmods.com/skyrimspecialedition/mods/18866)
[LegacyoftheDragonborn.esm](https://www.nexusmods.com/skyrimspecialedition/mods/11802/)
[BSAssets.esm and BSHeartland.esm](https://www.nexusmods.com/skyrimspecialedition/mods/10917)

Those are in the masterlist, so maybe something there could be causing an issue.
I'll test it out some more and see if I can figure it out.

**Comment by CptMcSplody** [comment]
Yeah if I remove the entry it works fine

```yaml
  - name: 'Alpine Forest of Whiterun Valley.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/18866' ]
    after:
      - 'BSHeartland.esm'
      - 'Unofficial Skyrim Special Edition Patch.esp'
    msg:
      - type: warn
        content:
          - lang: en
            text: '%1% is already included in this mod.'
          - lang: de
            text: '%1% ist bereits enthalten in diesem Mod.'
        subs:
          - '`Realistic High Altitude Treeline`'
        condition: 'active("Realistic Treeline.esp")'
    clean:
      - crc: 0xBD798EA8
        util: 'SSEEdit v3.2.70 EXPERIMENTAL'
```

**Comment by CptMcSplody** [comment]
Also starts working if I add a group in the masterlist for that entry.
```yaml
  - name: 'Alpine Forest of Whiterun Valley.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/18866/' ]
    group: *fixesGroup
```
