### ISSUE TITLE
.mohidden plugins are not distinguishable from normal plugins for loot

### ISSUE THREAD

**Issue by parsafaramarzi** [loot/loot#1131]
@Ortham your turn :D

**Comment by Ortham** [comment]
I think I might have misunderstood something - you say that plugins that have `.mohidden` appended to their filenames aren't distinguishable from normal plugins, does that mean they somehow appear in LOOT? I would expect LOOT to ignore them completely.

**Comment by CptMcSplody** [comment]
`.mohidden` plugins don't show up in LOOT, but they're still evaluated for conditions.

**Comment by CptMcSplody** [comment]
Same thing will happen with `.ghosted` though, so I guess it will have to be fixed in the condition.
![image](https://user-images.githubusercontent.com/1944639/61596323-a847e080-abf9-11e9-831d-240e32ad9a95.png)

**Comment by CptMcSplody** [comment]
```yaml
  - name: 'Scarcity - (2|4|6|8|10)x Loot Rarity\.esp'
    url: [ 'https://www.nexusmods.com/skyrim/mods/49496/' ]
    msg:
      - <<: *useOnlyOneX
        condition: 'many("Scarcity - (2|4|6|8|10)x Loot Rarity\.esp")'
        subs: [ 'Scarcity - Loot Rarity' ]
```
I'd need to exclude `.mohidden` and `.ghosted` from all these types of conditions.
I'll try using a negative lookahead not sure of the syntax though.
