### ISSUE TITLE
Support Skyrim Anniversary Edition (SSE)

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1620]
https://elderscrolls.bethesda.net/en/article/REybYU3Gy2InVlHmus4UC/skyrim-10th-anniversary-fan-celebration

> We’re also excited to announce the most definitive version of Skyrim to date: The Elder Scrolls V: Skyrim Anniversary Edition. The Anniversary Edition includes Skyrim Special Edition and 74 creations, all 48 currently available and 26 to be released. These showcase over 500+ individual elements such as quests, items, armor, houses, etc.

Bethesda recently announced **Skyrim Anniversary Edition**, a substantial update to SSE.
The update is scheduled to be released on the 11th of November 2021.

We now also have the following piece of information from **extrwi**, one of the SKSE developers:
https://www.reddit.com/r/skyrimmods/comments/q6czcc/pc_sse_an_important_psa_regarding_skyrim/

Some excerpts:
> The upcoming Anniversary Edition of Skyrim is going to be much more disruptive to the modding scene than is commonly believed. Back up your executable now, and disable updates in Steam.

> Bethesda has decided to update the compiler used to build the 64-bit version of Skyrim from Visual Studio 2015 to Visual Studio 2019. This changes the way that the code is generated in a way that forces mod developers to start from scratch finding functions and writing hooks.

> Plugins using the Address Library will need to be divided in to "pre-AE" and "post-AE" eras. Code signatures and hooks will need to be rewritten.

> Additionally, I can confirm that AE will be released as a patch to existing Special Edition installations, not as a separate game listing in Steam.

Most of the issues that arise if one uses SKSE and/or SKSE plugins should not be a problem regarding LOOT and load order sorting. There is the fact though, that SAE will be published as an update to SSE and a couple of questions follow out of that.
- Will this be a forced update? Or can I *choose* to opt into SAE (or deliberately stay on the SSE branch)?
- If this is a forced update, will the official name on the Steam page also be changed from SSE to SAE?
- What do we need to do, or should do, so that LOOT can differentiate between the two versions of the game? Since this is an update to an existing game, that apparently changes the game's "surname" (Special Edition -> Anniversary Edition), how should the game be called in LOOT's game selection dropdown menu (as well as our documentation)?
- If we can differentiate between SSE and SAE, should we warn LOOT users if they use a SKSE mod/plugin in conjunction with SAE, that was published under (and intended to be used with) SSE?

Relevant data from SSE's masterlist regarding SKSE:
```yaml
prelude:
  common:
  # Global Anchors
    - &scriptExtenderMissing
      type: error
      content:
        - lang: en
          text: 'You have installed an %1% plugin but %1% was not found! See %1% download page: %2%.'
       # Other languages omitted
      subs:
        - 'SKSE'
        - '[SKSE](https://skse.silverlock.org)'
      condition: 'file("SKSE/Plugins/([^\.]+\.dll)") and not file("../skse(64|vr)_loader\.exe")'

    - &scriptExtenderRequiredScripts
      type: warn
      content:
        - lang: en
          text: 'It appears you have installed **%1%**, but its required scripts seem to be missing. Please ensure you have correctly installed the scripts bundled with the **%2%** installation archive.'
       # Other languages omitted
      subs:
        - 'Skyrim Script Extender'
        - '[SKSE](https://skse.silverlock.org)'
      condition: 'not file("scripts/skse.pex") and ((file("../SkyrimSE.exe") and not file("SkyrimVR.esm") and file("../skse64_loader.exe")) or (file("../SkyrimVR.exe") and file("SkyrimVR.esm") and file("../sksevr_loader.exe")))'

common:
# File Anchors
  - &SKSE
    name: '../skse64_loader.exe'
    display: '**Skyrim Script Extender ([ SKSE 64 ](https://skse.silverlock.org))**'
    condition: 'file("../SkyrimSE.exe") and not file("SkyrimVR.esm") and not file("../skse64_loader.exe")'

  - &SKSE_VR
    name: '../sksevr_loader.exe'
    display: '**Skyrim Script Extender ([ SKSE VR ](https://skse.silverlock.org))**'
    condition: 'file("../SkyrimVR.exe") and file("SkyrimVR.esm") and not file("../sksevr_loader.exe")'
```
