### ISSUE TITLE
Partial Form flag for CELL, QUST, and WRLD Records

### ISSUE THREAD

**Issue by Glitchfinder** [loot/loot#1748]
Fallout 4 supports the Partial Form header flag ("Unknown 14" for most record types in xedit) for Quest, Worldspace, and interior Cell records. There is fairly thorough documentation on the flag for Skyrim LE in [this issue for TES5Edit](https://github.com/TES5Edit/TES5Edit/issues/752), including a translation of the loader routines into C++ by DavidJCobb. Something not covered in that issue is that in Fallout 4 (and possibly varying versions of Skyrim), exterior CELL records do not support the use of this flag and will lead to the apparent deletion of objects ingame if used.

The use of this flag on supported forms results in the game ignoring that form during the loading process. It will instead skip to child forms, such as the dialogues contained within a quest or the references contained within a cell. This is very advantageous for reducing mod conflicts, as proper use of the flag means a mod that adds a single object to a cell will not revert changes by another mod that adjusted the acoustic space, location, cell lighting, etc. Similar for quests versus dialogues and scenes, and worldspaces versus the cells they contain.

### Proposal:

Implement a warning under the following conditions:

1. A plugin contains an identical to master QUST record, WRLD record, or interior CELL record. (Interior CELL records as defined by not being a child of a WRLD record).
2. The above record does not have the "Partial Form" or "Unknown 14" flag set in its header.

This warning should ideally mention that the record makes no changes but can overwrite other mods that do make changes, possibly referring to a document on the partial form flag in the process.

Further, implement an additional warning under the following conditions:

1. A plugin contains an exterior CELL record (as defined by being the child of a WRLD record).
3. The above record does have the "Partial Form" or "Unknown 14" flag set.

This warning should mention that use of the "Partial Form" flag on an exterior CELL record can result in the removal of objects from the world, as anything in the flagged cell that is changed by the mod in question will fail to load in the game and behave as though it has been deleted or disabled.

**Comment by Ortham** [comment]
LOOT can't detect ITM records itself, so this functionality can't be supported without significant changes to plugin parsing.

**Comment by Glitchfinder** [comment]
That's fair, though it works under the assumption that the warning would be automated. Many of LOOT's warnings and ordering rules are user-submitted and rely on checksums. Is that not a viable approach here?

**Comment by Ortham** [comment]
> That's fair, though it works under the assumption that the warning would be automated. Many of LOOT's warnings and ordering rules are user-submitted and rely on checksums. Is that not a viable approach here?

Yes, that would be viable. If you just want messages added for certain CRCs, you can supply the relevant plugin names and CRCs similar to how dirty plugins can be reported, so that the masterlist maintainers know what to add - I think the technical detail you've provided is mostly unecessary for that (which is partly why I assumed you wanted this automated).

**Comment by pStyl3** [comment]
> possibly referring to a document on the partial form flag in the process

Is there any official/unofficial documentation regarding the Partial Form flag that we could link to, apart from the mentioned xEdit GitHub issue? Maybe @VlitS could help us here?

**Comment by VlitS** [comment]
Not really anything official, sorry. There is some discussion of it on the xEdit discord that resulted in that Github issue. The extent of my testing was verifying that it can be used to bypass the .esl bug with new CELLs in SSE*, and confirming that is is a decent idea to use it for ITM DIAL, CELL, and WRLD overrides when you are changing child records (e.g. editing/adding/removing REFRs) in general. 

That said, the original use of it by Bethesda seems to be primarily for the version control system. That Github issue is the most concentrated info on it that I can find.

Discord link to the start of the discussion that led to me making that issue (there were some earlier discussions I found using "partial form" as the search term that I read while writing it): https://discord.com/channels/471930020454072348/486317996344868864/647821372378054656.


If we want semi-official "documentation", someone should probably start a thread (on Nexusmods or elsewhere) with a summary of the info we know about it, should probably first discuss it on the xEdit discord to make sure the current consensus on it is accurate. Maybe check if [DavidJCobb](https://github.com/DavidJCobb) has any more info (digging into the program code is a little more accurate than just a handful of tests by one or two people :D )

*an interior CELL created by a plugin flagged both ESL and ESM (which all .esl plugins are treated by the game as having) will have all non-persistent placed objects fail to load if a later plugin overrides the CELL

**Comment by pStyl3** [comment]
Thanks for the detailed response @VlitS. In this case I agree that there first should be a consensus regarding the topic. Once that is reached the only question is, where that agreed upon consensus should be posted. Perhaps within the [Tome of xEdit](https://tes5edit.github.io/docs/)?

Here's a first suggestion on how this could be done within LOOT. We could create these two message anchors in the `prelude`, notice that I've given `&partialFormSet` the type `say` and `&partialFormReset` the type `warn`. Both messages are written with the assumption, that we can link to some sort of documentation for the flag.

prelude.yaml
```yaml
  - &partialFormSet
    type: say
    content:
      - lang: en
        text: 'The record **%1%** of this plugin can benefit from the Partial Form / Unknown 14 flag. See the [documentation](http://example.com/) for more information.
```
```yaml
  - &partialFormReset
    type: warn
    content:
      - lang: en
        text: 'The exterior CELL record **%1%** of this plugin has the Partial Form flag set, which can result in the removal of objects from the world. As such the Partial Form flag should be removed. See the [documentation](http://example.com/) for more information.
```

Then, within the `masterlist`:

masterlist.yaml
```yaml
  - name: 'ExamplePlugin1.esp'
    msg:
      - <<: *partialFormSet
        subs: [ '02001408' ]
        condition: 'checksum("ExamplePlugin1.esp", 1AE8D648)'

  - name: 'ExamplePlugin2.esp'
    msg:
      - <<: *partialFormReset
        subs: [ '02001408' ]
        condition: 'checksum("ExamplePlugin2.esp", 1AE8D648)'
```

With the above we could add these notifications on a `checksum` basis. What I'm asking myself is, if there are plugins with more than just a few of those incorrectly flagged records .. because if yes, that would mean that for `n` incorrectly flagged records we would need to assign these messages `n` times. If `n` is in the low single digits, no problem. If there are dozens of them or more, this wouldn't be practically anymore. So an even more generalised message might be better.

prelude.yaml
```yaml
  - &partialFormSet
    type: say
    content:
      - lang: en
        text: 'One or multiple records from this plugin can benefit from the Partial Form / Unknown 14 flag. See the [documentation](http://example.com/) for more information.
```
```yaml
  - &partialFormReset
    type: warn
    content:
      - lang: en
        text: 'One or multiple exterior CELL records of this plugin have the Partial Form flag set, which can result in the removal of objects from the world. As such the Partial Form flag should be removed. See the [documentation](http://example.com/) for more information.
```

And the corresponding entries in the `masterlist` for this variant:

masterlist.yaml
```yaml
  - name: 'ExamplePlugin3.esp'
    msg:
      - <<: *partialFormSet
        condition: 'checksum("ExamplePlugin3.esp", 1AE8D648)'

  - name: 'ExamplePlugin4.esp'
    msg:
      - <<: *partialFormReset
        condition: 'checksum("ExamplePlugin4.esp", 1AE8D648)'
```

**Comment by pStyl3** [comment]
Actually, no we wouldn't necessarily need to assign the message `n` times, if there are `n` records that are incorrectly flagged. We could write them all within the `subs` text in the masterlist.

So
```yaml
        subs: [ '02001408' ]
```

could then become
```yaml
        subs: [ '02001408 and 02001409 and 02001410' ]
```

We also could write them bold, so
```yaml
  - name: 'ExamplePlugin1.esp'
    msg:
      - <<: *partialFormSet
        subs: [ '**02001408** and **02001409** and **02001410**' ]
        condition: 'checksum("ExamplePlugin1.esp", 1AE8D648)'
```
