### ISSUE TITLE
Add support for Skyrim Special Edition from GOG

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1802]
Skyrim SE / AE was [just released on GOG](https://www.gog.com/en/news/release_the_elder_scrolls_v_skyrim), and it would be good for LOOT to support it out-of-the-box.

Apparently the game's local app data path is `%localappdata%\Skyrim Special Edition GOG` and registry keys have changed - the xEdit discord server may have more details.

**Comment by pStyl3** [comment]
[News on Nexus](https://www.nexusmods.com/news/14753)

**Comment by pStyl3** [comment]
I've bought the AE version from GOG and downloaded the offline files directly (so not through GOG Galaxy):

![tes1](https://user-images.githubusercontent.com/10406657/193237183-1db53ea4-051e-4f8a-9d05-9a830ad5b539.PNG)

**Comment by pStyl3** [comment]
Here's `GOG\Skyrim Anniversary Edition\` after using `setup_the_elder_scrolls_v_skyrim_special_edition_1.6.659.0.8_(64bit)_(59094).exe`:

![tes2](https://user-images.githubusercontent.com/10406657/193240731-f1e4c9b4-6796-4828-ad30-06e4794d84db.PNG)

![tes3](https://user-images.githubusercontent.com/10406657/193240745-cd4aad73-d8f7-4639-aa52-aa093796dc32.PNG)

**Comment by pStyl3** [comment]
Using `SkyrimSE.exe` will lead to this starting screen (at this point in time I haven't used the AE upgrade via `setup_the_elder_scrolls_v_skyrim_anniversary_upgrade_1.6.659.0.8_(64bit)_(59094).exe`):

![tes4](https://user-images.githubusercontent.com/10406657/193242163-707fd491-5a85-404d-ac1a-292f7f6c87e0.PNG)

**Comment by pStyl3** [comment]
> The game version is 1.6.659.0.
Game settings (INI files) are stored under "%userprofile%\Documents\My Games\Skyrim Special Edition GOG".
Saved games are stored under "%userprofile%\Documents\My Games\Skyrim Special Edition GOG\Saves".
Load order data (plugins.txt and loadorder.txt files) is stored under "%localappdata%\Skyrim Special Edition GOG".

Those infos from the Nexus article are correct, though my SSE GOG folder in localappdata is currently empty.

**Comment by pStyl3** [comment]
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\Games\1711230643`

![tes6](https://user-images.githubusercontent.com/10406657/193247460-665faf38-8b6a-4885-a8fc-c6d505edb2c9.png)

**Comment by sibir-ine** [comment]
Does it write to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim Special Edition` as well?

**Comment by pStyl3** [comment]
I don't think so, that one only has the `installed path` from Steam's SSE installation.

**Comment by pStyl3** [comment]
```yaml
  - name: 'Update.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0xC3E0D564
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 384
        udr: 92
        nav: 3
      - <<: *reqManualFix
        crc: 0xD48C1F25
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3

  - name: 'Dawnguard.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0xC855C37C
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 842
        udr: 82
        nav: 59
      - <<: *reqManualFix
        crc: 0x2199B5A4
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7
        nav: 59
      - <<: *reqManualFix
        crc: 0x4B45E434
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 59

  - name: 'HearthFires.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x073ECE89
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 221
        udr: 11
        nav: 5
      - <<: *reqManualFix
        crc: 0xFE84C98B
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 5

  - name: 'Dragonborn.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x7BE33EB9
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 87
        udr: 8
        nav: 1
      - <<: *reqManualFix
        crc: 0x369E7969
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1

  - name: 'ccBGSSSE001-Fish.esm'
    dirty:
      - <<: *quickClean
        crc: 0x3F2DC672
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
        udr: 4

  - name: 'ccQDRSSE001-SurvivalMode.esl'
    dirty:
      - <<: *quickClean
        crc: 0x87023079
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 1

  - name: 'ccBGSSSE037-Curios.esl'
    clean:
      - crc: 0xEA917D0B
        util: 'SSEEdit v4.0.4c'

  - name: 'ccBGSSSE025-AdvDSGS.esm'
    dirty:
      - <<: *quickClean
        crc: 0xA3D900E1
        util: '[SSEEdit v4.0.4c](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 3
```
