### ISSUE TITLE
Add support for the Epic distribution of Skyrim SE / AE

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1809]
Skyrim SE / AE was [released](https://store.epicgames.com/en-US/p/skyrim) on the Epic Games Store today. It would be good to support that distribution of the game, but they're selling SE for £35 and AE for £43 and I don't fancy paying that much for my fourth copy of Skyrim.

If anyone has a copy of Skyrim from EGS and would like LOOT to support it, I probably only need the following information:

- What Registry keys exist that point to the game's install path (the one that contains `SkyrimSE.exe`)
- What the game's local app data path is (e.g. `C:\Users\<user>\AppData\Local\Skyrim Special Edition` is the Steam release's path)

pStyl3 provided this information and more for the recent GOG release in #1802, see that issue for examples of what's needed.

No other Elder Scrolls or Fallout game is currently on EGS.

**Comment by BeermotorWB** [comment]
It looks to be very similar to the GOG version as far as paths go, just replace GOG with EPIC.
The executable version is 1.6.678.

**Comment by BeermotorWB** [comment]
md5sums for Steam, GOG, and Epic

```
Steam
a9a76ca74c41c09746486325df935480  ./Skyrim.esm
97540ec27c60c0aa72feafb0e6fecb19  ./Update.esm
eb61a975d63e91269cdbfcec4d07eace  ./Dawnguard.esm
d1f7497c93c249ac76c8e348235f9a47  ./Dragonborn.esm
e4fb48be1df21a8bd3c64ec990116b81  ./HearthFires.esm

EPIC
d06798e39b9eece7bc3ac48c33e35e62  ./Skyrim.esm
ae84a1815a793e393c57cdce5e1acb22  ./Update.esm
2e78ec15957dd0ca094381f7d899a94b  ./Dawnguard.esm
e9bf8bdec0f42b8bd7033df829d54d5f  ./Dragonborn.esm
e4e1f7ce5afd105d22e16aa86151b784  ./HearthFires.esm

GOG
14dc786feecc692d805c41ae25d2ff8a  ./Skyrim.esm
a1252426acbafe9217cb300891302661  ./Update.esm
47a5ab81f1069a4c4901874746c34c83  ./Dawnguard.esm
29d9bfbee236e9e86d655aa51fdac957  ./Dragonborn.esm
92c214a00afdf1c8bde308609300cc37  ./HearthFires.esm
```

**Comment by Silarn** [comment]
Though various sources I believe this may be correct info (I can't verify as I don't own it).

The directories have been renamed to "Skyrim Special Edition EPIC".

The AppId in the Epic Games manifest file is "ac82db5035584c7f8a2c548d98c86b2c". In the MO2 basic games code, we parse the manifest files in the `C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests` directory and search for the AppId matching whatever game we're searching for.

In the matching manifest, you can parse the "InstallLocation" for the game directory.

 Unless Skyrim is an exception, the Epic Launcher doesn't create registry entries for the game location.

Typically Epic Games packs the game exe with a copy of `EOSSDK-Win64-Shipping.dll` though I can't verify that.

**Comment by sibir-ine** [comment]
Thanks for the info, both of you! If SSE doesn't have `EOSSDK-Win64-Shipping.dll`, it should have a `.egstore` directory. @BeermotorWB, if you could verify Silarn's info, we'd appreciate it.

**Comment by BeermotorWB** [comment]
Confirmed Epic version has `EOSSDK-Win64-Shipping.dll`

**Comment by sibir-ine** [comment]
Also, can you please verify that it doesn't write to the `Bethesda Softworks` registry (i.e., `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim Special Edition`)?

**Comment by BeermotorWB** [comment]
### Masterlist entries for the Epic masters:

**Update.esm**
```
  - name: 'Update.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x0572C368
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 384
        udr: 92
        nav: 3
    dirty:
      - <<: *reqManualFix
        crc: 0x2BABA088
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3
```
**Dawnguard.esm**

```
  - name: 'Dawnguard.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x02A487C1
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 842
        udr: 82
        nav: 59
    dirty:
      - <<: *reqManualFix
        crc: 0xE0D5302B
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 7
        nav: 59
    dirty:
      - <<: *reqManualFix
        crc: 0x63B4EBD1
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 59
```
**Dragonborn.esm**

```
  - name: 'Dragonborn.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0xAF3D8E37
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 87
        udr: 8
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0xBF147A1A
        util: '[SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 1
```
