### ISSUE TITLE
Try building Flatpak from source

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1966]
Based on review feedback I got when initially creating LOOT's Flathub page, it's considered best practice to build Flatpak packages from source. LOOT doesn't currently do that, because it's a lot more complicated, but that does mean that maintenance requires more care, as the LOOT Linux binaries need to be built against the same shared library versions that will exist at runtime. This has recently become more of a pain than I thought it would, as I'm attempting to update to Qt 6.7.0.

I've found the process of running commands as part of building the Flatpak to be under-documented, and it wasn't obvious how to do things, but trial-and-error and looking at other Flatpak manifests have helped. What also helped was finding lists of what I can expect to be in the Flatpak build and runtime environments: LOOT uses the KDE runtime, and the KDE SDK's contents are listed [here](https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt6.7/org.kde.Sdk.json.in). The KDE SDK builds on top of the freedesktop SDK, which has its contents listed on pages linked to from [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/Release-Contents#contents).

The second complication is that Flatpak builds are sandboxed without network access, and all dependencies must be declared in a way that `flatpak-builder` understands so that it can fetch them before it runs the build. This is a problem:
  - Some dependencies that are installed using a system package manager (e.g. `apt`) are not present in the Flatpak build or runtime environments.
    - I think this only actually affects TBB,  though Boost will also need to be built by `flatpak-builder`.
  - Some dependencies are declared using CMake's `ExternalProject_Add` or `FetchContent` and are downloaded by CMake during the build.
  - Some dependencies are installed using `pip`.
  - Some dependencies are installed by `cargo` as part of the CMake build process.

## Boost & TBB

I think the relevant manifest entries for Boost and TBB would be:

```yaml
  - name: Boost
    buildsystem: simple
    build-commands:
      - ./bootstrap.sh --prefix=/app
      - ./b2 link=static runtime-link=shared variant=release cxxflags="-std=c++17 -fPIC" --with-locale install 
    sources:
      - type: archive
        url: https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.tar.bz2
        sha256: 7009fe1faa1697476bdc7027703a2badb84e849b7b0baad5086b087b971f8617

  - name: libtbb
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DTBB_TEST=OFF
    sources:
      - type: archive
        url: https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.12.0.tar.gz
        sha256: c7bb7aa69c254d91b8f0041a71c5bcc3936acb64408a1719aec0b2b7639dd84f
```

## CMake `FetchContent`

The only dependency that's managed using `FetchContent` is `tomlplusplus`. `FetchContent` can be configured to try `FindPackage` first, so running CMake for that dependency separately (like how `libtbb` is built above) like so seems to work:

```yaml
  - name: tomlplusplus
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
    sources:
      - type: archive
        url: https://github.com/marzer/tomlplusplus/archive/v3.3.0.tar.gz
        sha256: fc1a5eb410f3c67e90e5ad1264a1386d020067cfb01b633cc8c0441789aa6cf2
```

Having these entries in the Flatpak manifest does duplicate URLs and hashes between it and `CMakeLists.txt` but that seems unavoidable.

`FetchContent` is easier to deal with than `ExternalProject_Add` but doesn't provide as much separation between LOOT and its dependencies, so e.g. variables are shared between them and all their targets show up in the MSVC solution, which is a mess. This means I can't use `FetchContent` for all of LOOT's dependencies because some of them have targets with the same name.

`FetchContent` also only works for dependencies that provide the necessary config files that let CMake find them, or those that don't need building (`tomlplusplus` is both). For dependencies that are only the latter, I think I'd need to set `FETCHCONTENT_SOURCE_DIR_<uppercaseName>` to the directory that `flatpak-builder` installed the dependency to.

## CMake `ExternalProject_Add`

The easiest approach seems to be to make the URL for each dependency configurable, and to add each dependency's archive as an additional source, and configure the dependency's URL to be the path that `flatpak-builder` downloads that archive to.

A different approach will be needed for LOOT's libloot dependency though, as that's the only one that is downloaded as a binary, and it'll need to be built from source. Since it's needed at runtime, I think that should be handled as a separate module and installed, then that install detected and used by CMake. The alternative would end up with nested `ExternalProject_Add` invocations and more complicated dependency handling for the inner calls.

A disadvantage of this approach is that although LOOT and libloot use many of the same dependencies, this will build them twice.

## `pip` & `cargo`

There are helper scripts for converting cargo and pip dependency manifests into a format supported by flatpak-builder, they can be found [here](https://github.com/flatpak/flatpak-builder-tools). Those need to be run separately to the build process: in this repository that could be done in a preceding GitHub Actions step, but when building for Flathub I think the files would need to be committed to the repository so that they're present when the build starts. Those committed files would need to be regenerated whenever the dependencies changed, so that would need to be scripted and the script itself might need to be updated between releases.

## Misc.

If the Flatpak is built from source, then it would probably be best to remove the Linux archive as an artifact for CI and release builds. The CI build already produces a Flatpak artifact, but the rest of the build would be best adapted to only build and run the tests, to reduce the amount of duplicated effort - in fact, it would probably be best to run the Flatpak build and tests build as separate jobs so they can be done in parallel.

## Dependency tree

The build dependency tree looks something like this:

```
- LOOT
  - libloot
    - Boost
      - Header-only, doesn't seem to be in the SDK
    - ICU
      - Provided by the SDK
    - TBB
      - Needs to be built using CMake
    - Google Test
      - Needs to be built using CMake
    - esplugin
      - Needs cargo, installs dependencies using cargo
    - libloadorder
      - Needs cargo, installs dependencies using cargo
    - loot-condition-interpreter
      - Needs cargo, installs dependencies using cargo
    - testing-plugins
      - Since this is only used for tests, the build could be run to avoid this.
    - spdlog
      - Used as a header-only library
      - Depends on the fmt library, but bundles it
    - yaml-cpp
      - Needs to be built using CMake
    - Sphinx
      - It and its dependencies (sphinx_rtd_theme, breathe) are installed through pip, and need Python
      - Doesn't seem to be in the SDK
    - doxygen
      - Supplied by the freedesktop SDK
  - Boost
    - Boost.Locale needs to be built, doesn't seem to be in the SDK
  - OGDF
    - Needs to be built using CMake
  - ICU (see entry under libloot)
  - TBB (see entry under libloot)
  - Qt
    - Provided by the platform/SDK
  - Google Test (see entry under libloot)
  - zlib
    - Supplied by the freedesktop SDK
  - minizip-ng
    - Doesn't seem to be in the SDK
  - testing-plugins (see entry under libloot)
  - tomlplusplus
    - Used as a header-only library
  - spdlog (see entry under libloot)
  - ValveFileVDF
    - Used as a header-only library
  - Sphinx (see entry under libloot)
  - gettext
    - Supplied by the freedesktop SDK
```

I don't think there are any more nested layers of dependencies that require network access to build.
