### ISSUE TITLE
Add support for message string substitution

### ISSUE THREAD

**Issue by Ortham** [loot/loot#202]
Proposed syntax:

```
- &obsoleteUseLatest
  type: say
  content: 'Obsolete, upgrade to [latest version](%1%).'
  subs:
    - http://www.nexusmods.com/fallout3/mods/8909
```

This requires WrinklyNinja/yaml-cpp#2 to be fixed in order to be useful.
