### ISSUE TITLE
Masterlist parsing issue on Linux?

### ISSUE THREAD

**Issue by Ortham** [loot/loot#2076]
Reported by alekulyn on Discord [here](https://discord.com/channels/473542112974077963/496196499890241546/1346726748468805693) with the Fallout 4 masterlist, and S3ctor on Discord [here](https://discord.com/channels/473542112974077963/473542230095822848/1350716079004975144) with the Morrowind masterlist.

S3ctor's log entry:

```
[23:10:43.060445] [error]: An error occurred while parsing the metadata list(s): yaml-cpp: error at line 2661, column 9: bad conversion: 'type' key missing from 'message' object
```

alekulyn's log entry:

```
yaml-cpp: error at line 2624, column 5: bad conversion: 'type' key missing from 'message' object
```

alekulyn also shared some gdb ouput that suggests that maybe the YAML merge keys aren't getting resolved:

```
(gdb) f 10
#10 loot::MetadataList::Load (this=this@entry=0x7fffc77fcd60, istream=...,
    source_path=filesystem::path "/Games/Steam/steamapps/compatdata/377160/pfx/drive_c/users/steamuser/AppData/Local/Fallout4/masterlist.yaml" = {...})
    at /usr/src/debug/libloot/libloot-0.25.3/src/api/metadata_list.cpp:186
186           PluginMetadata plugin(node.as<PluginMetadata>());
(gdb) print YAML::Dump(node)
$23 = "name: UnofficialFallout4Patch.esp\nurl: [https://www.nexusmods.com/fallout4/mods/4526/]\ngroup: Fixes\nmsg: [{<<: {type: error, content: [{lang: en, text: \"Delete. Already included in {0}.\"}, {lang: bg, text: \"За изтриване. Включена е в {0}.\"}, {lang: da, text: \"Slet. Allerede inkluderet i {0}.\"}, {lang: de, text: \"Löschen. Bereits in {0} enthalten.\"}, {lang: es, text: \"Eliminar. Está incluido en {0}.\"}, {lang: fi, text: \"Poista. {0} sisältää jo tämän.\"}, {lang: fr, text: \"Supprimer. Déjà inclus dans {0}.\"}, {lang: it, text: \"Cancella. Già incluso in {0}.\"}, {lang: ja, text: \"削除してください。既に {0} に含
  れています。\"}, {lang: ko, text: \"삭제하십시오. 이미 {0}에 포함되어 있습니다.\"}, {lang: pl, text: \"Usuń. Już zawarte w {0}\"}, {lang: pt_BR, text: \"Apague. Já incluído em {0}\"}, {lang: pt_PT, text: \"Apagar. Já incluído em {0}.\"}, {lang: ru, text: \"Удалите. Уже включено в {0}.\"}, {lang: sv, text: \"Ta bort. Redan inkluderat i {0}.\"}, {lang: ta, text: \"நீக்கு. ஏற்கனவே {0} இல் சேர்க்கப்பட்டுள்ளது.\"}, {lang: tr_TR, text: \"Sil. Zaten {0} içinde yer alıyor.\"}, {lang: uk_UA, text: \"Видаліть. Уже додано у {0}.\"}, {lang: zh_CN, text: \"删除。已包含在{0}中。\"}]}, subs: [Unofficial Fallout 4 Patch], condition: active(\"Unofficial Fallout 4 Patch.esp\")}]"
```

Both users are running on Linux (alekulyn is using libloot v0.25 though the limo mod manager, while S3ctor is using LOOT itself).

I've been unable to replicate the issue on Windows or on Linux using LOOT v0.25.0 (tested on Windows using the Fallout 4 and Morrowind masterlists, and on Linux using the Morrowind masterlist).

**Comment by magicaldave** [comment]
I've been poking aruond at this for a few hours now and I have roughly the same trace alekulyn does I think. 

```
[0] from 0x00007ffff50ae63a in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))+26 at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:81
[1] from 0x00007ffff6ea1579 in YAML::convert<loot::Message>::decode(YAML::Node const&, loot::Message&)+-378699 at /usr/src/debug/libloot/libloot-0.25.3/src/api/metadata/yaml/message.h:65
[2] from 0x00007ffff6ea1579 in YAML::as_if<loot::Message, void>::operator()() const+-378674 at /usr/include/yaml-cpp/node/impl.h:131
[3] from 0x00007ffff6ea1579 in YAML::Node::as<loot::Message>() const+-378661 at /usr/include/yaml-cpp/node/impl.h:156
[4] from 0x00007ffff6ea1579 in YAML::convert<std::vector<loot::Message, std::allocator<loot::Message> > >::decode(YAML::Node const&, std::vector<loot::Message, std::allocator<loot::Message> >&)+-378231 at /usr/include/yaml-cpp/node/convert.h:320
[5] from 0x00007ffff6f38186 in YAML::as_if<std::vector<loot::Message, std::allocator<loot::Message> >, void>::operator()() const+54 at /usr/include/yaml-cpp/node/impl.h:131
[6] from 0x00007ffff6f38186 in YAML::Node::as<std::vector<loot::Message, std::allocator<loot::Message> > >() const+67 at /usr/include/yaml-cpp/node/impl.h:156
[7] from 0x00007ffff6f38186 in YAML::convert<loot::PluginMetadata>::decode(YAML::Node const&, loot::PluginMetadata&) [clone .isra.0]+1110 at /usr/src/debug/libloot/libloot-0.25.3/src/api/metadata/yaml/plugin_metadata.h:117
[8] from 0x00007ffff6ef5968 in YAML::as_if<loot::PluginMetadata, void>::operator()() const+155 at /usr/include/yaml-cpp/node/impl.h:131
[9] from 0x00007ffff6ef5968 in YAML::Node::as<loot::PluginMetadata>() const+168 at /usr/include/yaml-cpp/node/impl.h:156
[+]
```

It specifically throws when trying to parse this entry:
```
- name: '(adamantiumarmor|AreaEffectArrows|bcsounds|EBQ_Artifact|entertainers|LeFemmArmor|master_index|Siege at Firemoth).esp'
    url:
      - link: 'https://en.m.uesp.net/wiki/Morrowind:Plugins'
        name: 'Morrowind Official Plugins on UESP.net'
      - link: 'https://www.nexusmods.com/morrowind/mods/43931/'
        name: 'Unofficial Morrowind Official Plugins Patched'
    group: *earlyLoadersGroup
    msg:
      - <<: *alreadyInX
        subs: [ 'Unofficial Morrowind Official Plugins Patched' ]
        condition: 'active("Unofficial Morrowind Official Plugins Patched.ESP")'
      - <<: *deletePlugin
        subs: [ '"Unofficial Morrowind Official Plugins Patched.ESP"' ]
        condition: 'active("Unofficial Morrowind Official Plugins Patched.ESP")'
```

When it tries to cast as `PluginMetadata`, `node` looks like this: 
```
$19 = (const YAML::detail::iterator_value &) @0x7fffce846920: {
  <YAML::Node> = {
    m_isValid = true,
    m_invalidKey = "",
    m_pMemory = std::shared_ptr<YAML::detail::memory_holder> (use count 5, weak count 0) = {
      get() = 0x7fffb4003010
    },
    m_pNode = 0x7fffb43daf00
  }, 
  <std::pair<YAML::Node, YAML::Node>> = {
    first = {
      m_isValid = false,
      m_invalidKey = "",
      m_pMemory = std::shared_ptr<YAML::detail::memory_holder> (empty) = {
        get() = 0x0
      },
      m_pNode = 0x0
    },
    second = {
      m_isValid = false,
      m_invalidKey = "",
      m_pMemory = std::shared_ptr<YAML::detail::memory_holder> (empty) = {
        get() = 0x0
      },
      m_pNode = 0x0
    }
  }, <No data fields>}
```

I noticed at some point also that the AUR versions of loot and libloot were both old-ish, so I manually updated them to the latest release versions. 

I did also try the flatpak which didn't present this error but also couldn't read my user openmw.cfg at all. 

I get the impression that something in arch environments isn't being built correctly, but after some glancing over the respective build scripts for loot and libloot in both the repos and pkgbuilds I don't really see anything that strikes as meaningful. Notably, the same version of yaml-cpp is being used, which isn't surprising as it hasn't updated in nearly two years. Even the arch package for yaml-cpp itself doesn't really do anything unconventional with it.
