### ISSUE TITLE
Better support for "do not clean" flags

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#323]
At the moment, the minority of plugins that shouldn't be cleaned are labelled as such using a standard message. However, accidental use of non-standard messages and translation issues mean that it would be better if the "do not clean" state were flagged by some dedicated bit of syntax.

As it may be the case that other status flags may be useful in the future, a fairly generic mechanism could be implemented, such as:

```
 - name: Example.esp
   flags:
     - doNotClean
```

@loot/looters: Any thoughts?

**Comment by Freso** [comment]
I think it should be possible to set the flag on a per-version or per-crc basis, instead of (only) at the root level of a plugin.

**Comment by WrinklyNinja** [comment]
How about adding the flag to the existing dirty metadata structure, then? Maybe have it so that when the flag is present and the `udr` and `nav` counts are zero, the `util` key becomes optional, so there's no unnecessary data?

A possible implementation:

```
name: Example.esp
dirty:
   # Minimum data
   # will generate a message that includes "Do not clean any ITM records."
   - crc: 0x01234567
     cleanITMs: false
   # Optionally give the ITM count too
   # will generate a message that includes "Do not clean the ITM records."
   - itm: 5
     crc: 0x01234567
     cleanITMs: false
   # There is non-ITM dirt, so 'util' is needed
   # will generate a message that includes "Do not clean the ITM records."
   - itm: 5
     nav: 1
     crc: 0x01234567
     util: *dirtyUtil
     cleanITMs: false
```
