### ISSUE TITLE
LOOT API Bash Tag Generator Syntax error

### ISSUE THREAD

**Issue by Sharlikran** [loot/loot#444]
```yaml
  - name: TamrielTravellersItemsNPC.esp
    tag:
      - Deactivate
      - Delev
      - Filter
      - Relev
      - "-"
      - NoMerge
```
The bash tag generator is converting [-NoMerge](https://github.com/loot/oblivion/blob/master/masterlist.yaml#L8594) to the above syntax.  

- If it isn't a bug does the LOOT API use the "-" to indicate that the succeeding bash tag should be queued for removal in Wrye Bash?
- If it is a bug then until there is a fix or workaround for the issue, should I remove all the minus symbols and their respective Bash Tags from the taglist?

The old BOSS taglist.txt from 304.3 had the following syntax.
```
TamrielTravellersItemsNPC.esp
 TAG: {{BASH: Filter, Delev, Relev, Deactivate}} and remove [NoMerge] tag.
Oblivion WarCry EV.esp
 TAG: {{BASH: Actors.ACBS, Actors.AIData, Actors.DeathItem, Actors.Stats, Delev, Graphics, Invent, Relev, Stats}}
 IFVERSION("Oblivion WarCry EV.esp","1.09",<) TAG: Remove [Actors.DeathItem] tag for version 1.08 and below. More info("http://u.to/PCQMAg")
 DIRTY: Do not clean. "Dirty" edits are intentional and required for the mod to function.
```

LOOT Syntax question:
```yaml
  - name: 'Unofficial Oblivion Patch.esp'
    tag:
      [all the tags]
      - name: "-C.Water"
        condition: 'version("Unofficial Oblivion Patch.esp","3.4.0",>=)'
```
Will the LOOT API preserve the condition and invoke Wrye Bash to remove the tag if present?

**Comment by WrinklyNinja** [comment]
What Bash Tag generator are you talking about?

Your syntax questions are covered in the [documentation](https://loot.github.io/docs/0.7.0/LOOT%20Metadata%20Syntax.html#structs-tag). Specifically,

* LOOT does use a preceding `-` to indicate tags for removal.
* You shouldn't remove the minus symbols, because while they're suggesting the opposite of what they should, the result is that the suggestion has no effect. Removing them would create code churn for no benefit.
* Yes, LOOT's API will evaluate conditions when `loot_eval_lists()` is called.

**Comment by Sharlikran** [comment]
I mean mktaglist.py used with wrye bash to generate the taglist.yaml file.  I wasn't sure if I should open a ticket here or not.  Let me know if it's better to open it there.

**Comment by Sharlikran** [comment]
After adding the condition to the LOOT masterlist for Oblivion now I get the following.
```yaml
      - name: -C.Water
        condition: version("Unofficial Oblivion Patch.esp","3.4.0",>=)
```
However, Bash tags with the "-" but no condition are still being written like this.
```yaml
  - name: TamrielTravellersItemsNPC.esp
    tag:
      - Deactivate
      - Delev
      - Filter
      - Relev
      - "-"
      - NoMerge
```
