### ISSUE TITLE
Support Named Message String Substitution

### ISSUE THREAD

**Issue by egocarib** [loot/loot#452]
It would be cool if named specifiers could be used in addition to numeric specifiers for message string substitution.

Currently, the `subs:` key accepts a block sequence of substitutions. Those substitutions are then inserted into the message string based on sequential numeric specifiers (%1%, %2%, etc.)

Here's an example from the Metadata Syntax documentation:
```
type: say
content: 'A newer version of %1% [is available](%2%).
subs:
  - 'this plugin'
  - 'http://www.example.com'
```

This works good in an example like the one above, but might be confusing if substitution is used on a larger scale. For example, if we convert the example above into an anchor, we'd have something like the following:

```
- &newVersionAvailable
  type: say
  content: 'A newer version of %1% [is available](%2%).

# ...

- name: 'SomePlugin.esp'
  msg:
    - <<: *newerVersionAvailable
      subs:
        - 'this plugin'
        - 'http://www.example.com'
```

In this case, the YAML for a plugin entry is hard to read because it's not clear what the substitutions are supposed to be standing in for. It might also lead to mistakes if someone puts the substitutions out of order when editing the masterfile.

With named substitutions, I would envision something more like this, which I think is easier to read and more user-friendly:

```
- &newVersionAvailable
  type: say
  content: 'A newer version of %pluginName% [is available](%updateLink%).

# ...

- name: 'SomePlugin.esp'
  msg:
    - <<: *newerVersionAvailable
      subs:
        pluginName: 'this plugin'
        updateLink: 'http://www.example.com'
```

**Comment by WrinklyNinja** [comment]
I use [Boost.Format](http://www.boost.org/doc/libs/1_58_0/libs/format/doc/format.html) internally, which doesn't support named specifiers, so I'd need to do something else to support this.

However, I don't think the message is clear even if named specifiers are used, because there is still no context. If you want to understand the substitutions, you really need to know what the message says, so you'd need to refer back to the anchor anyway.

Using named specifiers does make the semantics of the substitutions in the anchor string clearer, but I'd suggest that a comment would do almost as good a job.

Eg.

```
# %1% is a plugin name, %2% is a URL.
- &newVersionAvailable
  type: say
  content: 'A newer version of %1% [is available](%2%).

# ...

- name: 'SomePlugin.esp'
  msg:
    - <<: *newerVersionAvailable
      subs:
        - 'this plugin'
        - 'http://www.example.com'
```

I don't really think the small benefit you'd get from named specifiers is worth the additional code complexity, especially since the existing numerical system would have to be supported too for backwards compatibility.
