### ISSUE TITLE
Masterlist conditions fail

### ISSUE THREAD

**Issue by Ortham** [loot/loot#65]
The `regex()`, `version()` and `active()` conditions are returning false when they should be true.

Test case:

```
    msg:
      - type: warn
        content: File works.
        condition: file("..\skse_loader.exe")
      - type: warn
        content: Regex works.
        condition: regex("Unofficial.+\.esp")
      - type: warn
        content: Checksum works.
        condition: checksum("Update.esm", E5B67BDA)
      - type: warn
        content: Version works.
        condition: version("Unofficial Dawnguard Patch.esp", "1.2.3", ==)
      - type: warn
        content: Active works.
        condition: active("Update.esm")
```
