### ISSUE TITLE
Remember window size and position

### ISSUE THREAD

**Issue by Ortham** [loot/loot#71]
Suggested by Surazal. Windows that need their positions and sizes recorded:
- Main
- Full editor
- Mini editor
- Report viewer
- Settings

YAML structure for holding values:

```
windows:
  main: # or fullEditor, miniEditor, viewer, settings
    xPos: <value>
    yPos: <value>
    height: <value>
    width: <value>
```
