### ISSUE TITLE
Change settings file format from YAML to remove yaml-cpp dependency

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#832]
The LOOT settings file is currently a YAML file, read and written using yaml-cpp. YAML was chosen
for its human-readability, and because LOOT was already using yaml-cpp for other things anyway. 

However, YAML is far more complex than necessary, and LOOT won't be using yaml-cpp for anything else once #830 is done. Probably the best choice for a replacement is TOML: it's a simple format that's very human-readable, and specifically targets configuration files.

The trouble with this is that YAML is complex enough that yaml-cpp can't really be replaced by a simpler parser, even specially targeting the settings file, so to actually simplify the code means breaking compatibility with existing versions of LOOT. 

The best mitigation I can currently think of is to to add a page to LOOT's website that people can copy/paste their settings.yaml into and get a settings.toml out, with instructions on the download page and in the first time tips dialog to do so.

---

Here's a three-way comparison of my LOOT config file as YAML, TOML and JSON:

## YAML

```yaml
window:
  top: 53
  bottom: 954
  maximised: false
  right: 2345
  left: 1218
lastGame: Skyrim Special Edition
language: en
lastVersion: 0.11.0
updateMasterlist: true
enableDebugLogging: true
game: auto
filters:
  hideVersionNumbers: false
  hideCRCs: false
games:
  - type: Oblivion
    name: "TES IV: Oblivion"
    folder: Oblivion
    master: Oblivion.esm
    repo: https://github.com/loot/oblivion.git
    branch: v0.10
    path: ""
    registry: Software\Bethesda Softworks\Oblivion\Installed Path
  - folder: Skyrim
    name: "TES V: Skyrim"
    type: Skyrim
    repo: https://github.com/loot/skyrim.git
    master: Skyrim.esm
    branch: v0.10
    path: ""
    registry: Software\Bethesda Softworks\Skyrim\Installed Path
  - type: Skyrim Special Edition
    name: "TES V: Skyrim Special Edition"
    folder: Skyrim Special Edition
    master: Skyrim.esm
    path: C:\Games\Steam\steamapps\common\Skyrim Special Edition\
    repo: https://github.com/loot/skyrim.git
    branch: v0.10
    registry: Software\Bethesda Softworks\Skyrim Special Edition\Installed Path
  - folder: Fallout3
    master: Fallout3.esm
    repo: https://github.com/loot/fallout3.git
    type: Fallout3
    name: Fallout 3
    branch: v0.10
    registry: Software\Bethesda Softworks\Fallout3\Installed Path
    path: ""
  - type: FalloutNV
    name: "Fallout: New Vegas"
    master: FalloutNV.esm
    folder: FalloutNV
    repo: https://github.com/loot/falloutnv.git
    registry: Software\Bethesda Softworks\FalloutNV\Installed Path
    path: ""
    branch: v0.10
  - registry: Software\Bethesda Softworks\Fallout4\Installed Path
    repo: https://github.com/loot/fallout4.git
    branch: v0.10
    master: Fallout4.esm
    path: C:\Games\Steam\steamapps\common\Fallout 4\
    type: Fallout4
    name: Fallout 4
    folder: Fallout4
  - type: Oblivion
    name: Nehrim - At Fate's Edge
    folder: Nehrim
    repo: https://github.com/loot/oblivion.git
    master: Nehrim.esm
    branch: v0.10
    path: ""
    registry: Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1\InstallLocation
```

## TOML

```toml
game = "auto"
lastGame = "Skyrim Special Edition"
language = "en"
lastVersion = "0.11.0"
updateMasterlist = true
enableDebugLogging = true

[window]
maximised = false
top = 53
bottom = 954
left = 1218
right = 2345

[filters]
hideVersionNumbers = false
hideCRCs = false

[[games]]
type = "Oblivion"
name = "TES IV: Oblivion"
folder = "Oblivion"
master = "Oblivion.esm"
repo = "https://github.com/loot/oblivion.git"
branch = "v0.10"
path = ''
registry = 'Software\Bethesda Softworks\Oblivion\Installed Path'

[[games]]
type = "Skyrim Special Edition"
name = "TES V: Skyrim Special Edition"
folder = "Skyrim Special Edition"
master = "Skyrim.esm"
path = 'C:\Games\Steam\steamapps\common\Skyrim Special Edition\'
repo = "https://github.com/loot/skyrim.git"
branch = "v0.10"
registry = 'Software\Bethesda Softworks\Skyrim Special Edition\Installed Path'

[[games]]
folder = "Fallout3"
master = "Fallout3.esm"
repo = "https://github.com/loot/fallout3.git"
type = "Fallout3"
name = "Fallout 3"
branch = "v0.10"
registry = 'Software\Bethesda Softworks\Fallout3\Installed Path'
path = ''

[[games]]
type = "FalloutNV"
name = "Fallout: New Vegas"
master = "FalloutNV.esm"
folder = "FalloutNV"
repo = "https://github.com/loot/falloutnv.git"
registry = 'Software\Bethesda Softworks\FalloutNV\Installed Path'
path = ''
branch = "v0.10"

[[games]]
type = "Fallout4"
name = "Fallout 4"
registry = 'Software\Bethesda Softworks\Fallout4\Installed Path'
repo = "https://github.com/loot/fallout4.git"
branch = "v0.10"
master = "Fallout4.esm"
path = 'C:\Games\Steam\steamapps\common\Fallout 4\'
folder = "Fallout4"

[[games]]
type = "Oblivion"
name = "Nehrim - At Fate's Edge"
folder = "Nehrim"
repo = "https://github.com/loot/oblivion.git"
master = "Nehrim.esm"
branch = "v0.10"
path = ''
registry = "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Nehrim - At Fate's Edge_is1\\InstallLocation"
```

## JSON

```json
{
  "game": "auto",
  "lastGame": "Skyrim Special Edition",
  "language": "en",
  "lastVersion": "0.11.0",
  "updateMasterlist": true,
  "enableDebugLogging": true,
  "window": {
    "maximised": false,
    "top": 53,
    "bottom": 954,
    "left": 1218,
    "right": 2345
  },
  "filters": {
    "hideVersionNumbers": false,
    "hideCRCs": false
  },
  "games": [
    {
      "type": "Oblivion",
      "name": "TES IV: Oblivion",
      "folder": "Oblivion",
      "master": "Oblivion.esm",
      "repo": "https://github.com/loot/oblivion.git",
      "branch": "v0.10",
      "path": "",
      "registry": "Software\\Bethesda Softworks\\Oblivion\\Installed Path"
    },
    {
      "type": "Skyrim Special Edition",
      "name": "TES V: Skyrim Special Edition",
      "folder": "Skyrim Special Edition",
      "master": "Skyrim.esm",
      "path": "C:\\Games\\Steam\\steamapps\\common\\Skyrim Special Edition\\",
      "repo": "https://github.com/loot/skyrim.git",
      "branch": "v0.10",
      "registry": "Software\\Bethesda Softworks\\Skyrim Special Edition\\Installed Path"
    },
    {
      "folder": "Fallout3",
      "master": "Fallout3.esm",
      "repo": "https://github.com/loot/fallout3.git",
      "type": "Fallout3",
      "name": "Fallout 3",
      "branch": "v0.10",
      "registry": "Software\\Bethesda Softworks\\Fallout3\\Installed Path",
      "path": ""
    },
    {
      "type": "FalloutNV",
      "name": "Fallout: New Vegas",
      "master": "FalloutNV.esm",
      "folder": "FalloutNV",
      "repo": "https://github.com/loot/falloutnv.git",
      "registry": "Software\\Bethesda Softworks\\FalloutNV\\Installed Path",
      "path": "",
      "branch": "v0.10"
    },
    {
      "type": "Fallout4",
      "name": "Fallout 4",
      "registry": "Software\\Bethesda Softworks\\Fallout4\\Installed Path",
      "repo": "https://github.com/loot/fallout4.git",
      "branch": "v0.10",
      "master": "Fallout4.esm",
      "path": "C:\\Games\\Steam\\steamapps\\common\\Fallout 4\\",
      "folder": "Fallout4"
    },
    {
      "type": "Oblivion",
      "name": "Nehrim - At Fate's Edge",
      "folder": "Nehrim",
      "repo": "https://github.com/loot/oblivion.git",
      "master": "Nehrim.esm",
      "branch": "v0.10",
      "path": "",
      "registry": "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Nehrim - At Fate's Edge_is1\\InstallLocation"
    }
  ]
}
```
